import { StyleSheet } from 'react-native';
export const mainStyle = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
  },
  header: {
    fontSize: 25,
    padding: 4,
    paddingBottom: 15,
    marginBottom: 10,
  },
  searchBar: {
    borderWidth: 1,
    padding: 10,
    flex: 1,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 20,
    paddingLeft: 0,
    color: '#000000',
  },
  wrapper: {
    margin: 20,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 0,
  },
  searchBtn: {
    position: 'absolute',
    left: 0,
    top: 0,
  },
  headerBlocks: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    marginBottom: 30,
    marginTop: 30,
    maringLeft: 10,
    marginRight: 10,
  },
  map: {
    width: 340,
    height: 200,
    borderRadius: 6,
  },
  wrapperBlock: {
    margin: 24,
    marginTop: 0,
  },
  flatDescription: {
    borderWidth: 0.5,
    borderRadius: 10,
    width: 160,
    height: 133,
    margin: 6,
    position: 'relative',
  },
  mock: {
    borderRadius: 6,
    flex: 1,
    backgroundColor: '#EEEEEE',
    zIndex: -1,
  },
  flatWrapper: {
    display: 'flex',
    alignContent: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  moreInfoFlats: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  plashka: {
    backgroundColor: '#5A46DE',
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    position: 'absolute',
    borderRadius: 6,
    zIndex: 100,
    top: 10,
    right: 10,
    bottom: 0,
    width: 50,
    height: 27,
  },
  wrapperBadge: {
    position: 'absolute',
    top: 30,
    right: 20,
    zIndex: 100,
  },
  nameWrapper: {
    display: 'flex',
  },
  nameHolder: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 20,
  },
  extraText: {
    color: 'gray',
  },
  btn: {
    backgroundColor: '#5A46DE',
    borderRadius: 4,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 40,
    marginVertical: 30,
  },
});
